nice_names = {

	'Y' : 'Y',
	'Z' :   'Z',
	'W' :   'W',
	'Oakland_Inner_Harbor' :   'Oakland Inner Harbor',
	'X' :   'X',
	'S1' :   'S1',
	'S2' :  'S2',
	'T2' :   'T2',
	'T1' :  'T1',
	'U2' :  'U2',
	'U1' : 'U1',
	'V' :'V',
	'A' : 'A',
	'B' :  'B',
	'C' : 'C',
	'D' :  'D',
	'E' :  'E',
	'F' :  'F',
	'G' :  'G',
	'H' :  'H',
	'I' :  'I',
	'J' :  'J',
	'K' :  'K',
	'L' :  'L',
	'LSB' :   'Lower South Bay',
	'SB_RMP' :   'South Bay (RMP)',
	'SB_RMP_west_shoal' :  'South Bay West Shoal (RMP)',
	'SB_RMP_channel' :  'South Bay Channel (RMP)',
	'SB_RMP_east_shoal' :  'South Bay East Shoal (RMP)',
	'SB_WB' :   'South Bay (Water Board)',
	'SB_WB_north_half' :   'South Bay North Half (Water Board)',
	'SB_WB_south_half' :   'South Bay South Half (Water Board)\nsame as South Bay (RMP)',
	'SB_WB_west_shoal' :   'South Bay West Shoal (Water Board)',
	'SB_WB_channel' :   'South Bay Channel (Water Board)',
	'SB_WB_east_shoal' :   'South Bay East Shoal (Water Board)',
	'SB_WB_west_shoal_north_half' :  'South Bay West Shoal North Half (Water Board)',
	'SB_WB_channel_north_half' :   'South Bay Channel North Half (Water Board)',
	'SB_WB_east_shoal_north_half' :   'South Bay East Shoal North Half (Water Board)',
	'SB_WB_west_shoal_south_half' :   'South Bay West Shoal South Half (Water Board)\nsame as South Bay West Shoal (RMP)',
	'SB_WB_channel_south_half' :   'South Bay Channel South Half (Water Board)\nsame as South Bay Channel (RMP)',
	'SB_WB_east_shoal_south_half' :   'South Bay East Shoal South Half (Water Board)\nsame as South Bay East Shoal (RMP)',
	'SB_RMP+5kmN_west_shoal' :   'SB_RMP+5kmN_west_shoal',
	'SB_RMP+5kmN_channel' :   'SB_RMP+5kmN_channel',
	'SB_RMP+5kmN_east_shoal' :   'SB_RMP+5kmN_east_shoal',
	'SB_RMP-5kmS_west_shoal' :  'SB_RMP-5kmS_west_shoal',
	'SB_RMP-5kmS_channel' :  'SB_RMP-5kmS_channel',
	'SB_RMP-5kmS_east_shoal' :   'SB_RMP-5kmS_east_shoal',
	'Berkeley_Marina' :   'Berkeley Marina',
	'RB' :   'RB',
	'Alcatraz_Whirlpool' :   'Alcatraz Whirlpool',
	'Larkspur_Ferry' :  'Larkspur Ferry',
	'Petaluma' :   'Petaluma River',
	'Sonoma' :  'Sonoma River',
	'Napa' :  'Napa River',
	'Stockton_Channel_Suisun_Bay' :  'Stockton Channel (Suisun Bay)',
	'Sacramento_Channel' : 'Sacramento Channel',
	'Roe_Island' :  'Roe Island',
	'Grizzly_Bay' :  'Grizzly Bay',
	'Squiggly_Creek' :   'Squiggly Creek (Suisun)',
	'Suisun-Fairfield' :   'Suisun-Fairfield',
	'Suisun_Slough' :   'Suisun Slough',
	'Delta_Boundary' :   'Delta Boundary',
	'Chipps_Island' :  'Chipps Island',
	'Y2' :  'Y2',
	'CB_East_Exchange' :   'Central Bay East Exchange',
	'Suisun_Bay' :   'Suisun Bay',
	'San_Pablo_Bay' :   'San Pablo Bay',
	'Central_Bay_RMP' :   'Central Bay (RMP)',
	'Central_Bay_WB' :   'Central Bay (Water Board)',
	'San_Pablo_Exchange' :  'San Pablo Exchange',
	'San_Pablo_Shoal' :  'San Pablo NW Shoal',
	'San_Pablo_Channel' :   'San Pablo Channel',
	'SE_San_Pablo_Shoal' :  'San Pablo SE Shoal',
	'Whole_Bay' : 'Whole Bay'}	